plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '1.0.24'
}

version = '1.3.1'
group = 'com.wjyyz.vindicator_slayer'

base {
    archivesName = 'vindicator_slayer'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

neoForge {
    // NeoForge for Minecraft 1.21.1
    version = '21.1.250'

    runs {
        client {
            client()
        }
        server {
            server()
        }
    }

    mods {
        vindicator_slayer {
            sourceSet sourceSets.main
        }
    }
}
